### PR TITLE
Create ja.json

### PR DESCRIPTION
**Pull request by taikun114**
Add Japanese translation.

### CODE REVIEW

**Comment by zhbjsh** [comment]
Hi, thank you very much for providing translations for the integration! I released a new version today with some new strings added, if you could translate them as well, I will integrate it into the next version!

**Comment by taikun114** [comment]
Thanks for response.
I added a new translation, but sorry, I think I made a mistake because I am a GitHub newbie.
Should I open a new pull request?

**Comment by zhbjsh** [comment]
Sorry, I had to update the strings again... If you have time, please translate the ones from the current version 1.0.0 and open a new pull request, so i can merge it. Thanks again!

**Comment by taikun114** [comment]
I see, thank you!
I have just translated it and will open a new pull request.

**Pull request closed without merging**
